exp_name: CLS_gif_cifar100
task: classification
seed: 0

data:
  dataset: CIFAR100
  root: ${DIFFDA_ROOT}/datasets
  resolution: 224
  num_classes: 100
  examples_per_class: -1

generation:
  method: GIF
  exp: gif_cifar100_seed0
  root_dir: ${DIFFDA_ROOT}/DiffDA-Eval/generated_images
  utilize_way: FC

model:
  arch: resnet50
  weights: None

training:
  batch_size: 32
  optimizer: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  num_epochs: 100
  criterion: CrossEntropy
