exp_name: CLS_gif_caltech101
task: classification
seed: 0

data:
  dataset: Caltech101
  root: ${DIFFDA_ROOT}/datasets
  resolution: 224
  num_classes: 97
  examples_per_class: -1

generation:
  method: GIF
  exp: gif_caltech101_seed0
  root_dir: ${DIFFDA_ROOT}/DiffDA-Eval/generated_images
  utilize_way: FC

model:
  arch: resnet50
  weights: None

training:
  batch_size: 32
  optimizer: sgd
  lr: 0.01
  momentum: 0.9
  weight_decay: 1e-4
  num_epochs: 100
  criterion: CrossEntropy
