exp_name: CLS_gif_blood_shot25
task: classification
seed: 0

data:
  dataset: Blood-25
  root: /your/path/to/datasets
  resolution: 224
  num_classes: 8
  examples_per_class: -1

generation:
  method: GIF
  exp: gif_blood_shot25_sd15_seed0
  root_dir: /your/path/to/DiffDA-Eval/generated_images

model:
  arch: resnet50
  weights: None

training:
  batch_size: 256
  optimizer: sgd
  lr: 0.01
  momentum: 0.9
  weight_decay: 5e-4
  num_epochs: 100
  criterion: CrossEntropy
