exp_name: GEN_da_fusion_blood_shot25
task: generation
seed: 0

data:
  dataset: Blood-25
  root: ${DIFFDA_ROOT}/datasets
  resolution: 512
  num_classes: 8
  examples_per_class: -1

generation:
  method: DAFusion
  sd_model: ${DIFFDA_ROOT}/ckpts/stable-diffusion-v1-5
  scheduler: DPMSolver++
  num_inference_steps: 25
  augment_ratio: 5
  strength: 0.3
  root_dir: ${DIFFDA_ROOT}/DiffDA-Eval/generated_images
  ti_embeds: ${DIFFDA_ROOT}/DiffDA-Eval/finetuned_generators/text_inversion/Blood-25_shot-1_seed0
