exp_name: CLS_diff_ii_aircraft_shot5
task: classification
seed: 0

data:
  dataset: Aircraft
  root: ${DIFFDA_ROOT}/datasets
  resolution: 224
  num_classes: 100
  examples_per_class: 5

generation:
  method: DiffII
  exp: diff_ii_aircraft_shot5_seed0
  root_dir: ${DIFFDA_ROOT}/DiffDA-Eval/generated_images
  utilize_way: GRR
  replace_prob: 0.5

model:
  arch: resnet50
  weights: "IMAGENET1K_V1"

training:
  batch_size: 256
  optimizer: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  num_epochs: 128
  criterion: LabelSmoothing
