exp_name: GEN_diff_mix_skin_shot50
task: generation
seed: 0

data:
  dataset: Skin-50
  root: /your/path/to/datasets
  resolution: 512
  num_classes: 7
  examples_per_class: -1

generation:
  method: DiffMix
  sd_model: /your/path/to/ckpts/stable-diffusion-v1-5
  scheduler: DPMSolver++
  num_inference_steps: 25
  augment_ratio: 5
  strength: 0.5
  root_dir: /your/path/to/DiffDA-Eval/generated_images
  ti_embeds: /your/path/to/DiffDA-Eval/finetuned_generators/text_inversion/Skin-50_shot-1_seed0
  db_lora_weights: /your/path/to/DiffDA-Eval/finetuned_generators/dreambooth/TEmb_Skin-50_shot-1_seed0
