exp_name: GEN_real_guidance_caltech101
task: generation
seed: 0

data:
  dataset: Caltech101
  root: ${DIFFDA_ROOT}/datasets
  resolution: 512
  num_classes: 97
  examples_per_class: -1

generation:
  method: RealGuidance
  sd_model: ${DIFFDA_ROOT}/ckpts/stable-diffusion-v1-5
  scheduler: DPMSolver++
  num_inference_steps: 25
  augment_ratio: 5
  strength: 0.9
  root_dir: ${DIFFDA_ROOT}/DiffDA-Eval/generated_images
