exp_name: CLS_da_fusion_cifar100
task: classification
seed: 0

data:
  dataset: CIFAR100
  root: /your/path/to/datasets
  resolution: 224
  num_classes: 100
  examples_per_class: -1

generation:
  method: DAFusion
  exp: da_fusion_cifar100_all_sd15_seed0
  root_dir: /your/path/to/DiffDA-Eval/generated_images
  replace_prob: 0.5

model:
  arch: resnet50
  weights: None

training:
  batch_size: 256
  optimizer: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  num_epochs: 100
  criterion: CrossEntropy
