exp_name: GEN_diff_ii_aircraft_shot10
task: generation
seed: 0

data:
  dataset: Aircraft
  root: ${DIFFDA_ROOT}/datasets
  resolution: 512
  num_classes: 100
  examples_per_class: 10

generation:
  method: DiffII
  sd_model: ${DIFFDA_ROOT}/ckpts/stable-diffusion-v1-5
  num_inference_steps: 25
  augment_ratio: 5
  split_ratio: 0.3
  root_dir: ${DIFFDA_ROOT}/DiffDA-Eval/generated_images
  inv_cache_dir: ${DIFFDA_ROOT}/DiffDA-Eval/cache/ddim_inversions
  ti_embeds: ${DIFFDA_ROOT}/DiffDA-Eval/finetuned_generators/text_inversion/Aircraft_shot10_seed0
  db_lora_weights: ${DIFFDA_ROOT}/DiffDA-Eval/finetuned_generators/dreambooth/TEmb_Aircraft_shot10_seed0
