exp_name: CLS_diffuse_mix_caltech101_mobilenet
task: classification
seed: 0

data:
  dataset: Caltech101
  root: /your/path/to/datasets
  resolution: 224
  num_classes: 97
  examples_per_class: -1

generation:
  method: DiffuseMix
  exp: diffuse_mix_caltech101_sd15_seed42
  root_dir: /your/path/to/DiffDA-Eval/generated_images

model:
  arch: mobilenet_v3_large
  weights: None

training:
  batch_size: 256
  optimizer: sgd
  lr: 0.03
  momentum: 0.9
  weight_decay: 1e-4
  num_epochs: 100
  criterion: CrossEntropy
