exp_name: CLS_real_guidance_cub_shot10
task: classification
seed: 0

data:
  dataset: Birds
  root: ${DIFFDA_ROOT}/datasets
  resolution: 224
  num_classes: 200
  examples_per_class: 10

generation:
  method: RealGuidance
  exp: real_guidance_cub_sd15_seed0
  root_dir: ${DIFFDA_ROOT}/DiffDA-Eval/generated_images
  utilize_way: GRR
  replace_prob: 0.3

model:
  arch: resnet50
  weights: "IMAGENET1K_V1"

training:
  batch_size: 256
  optimizer: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  num_epochs: 128
  criterion: LabelSmoothing
