exp_name: GEN_gif_aircraft_shot5
task: generation
seed: 0

data:
  dataset: Aircraft
  root: ${DIFFDA_ROOT}/datasets
  resolution: 512
  num_classes: 100
  examples_per_class: 5

generation:
  method: GIF
  sd_model: ${DIFFDA_ROOT}/ckpts/stable-diffusion-v1-5
  clip_model: ${DIFFDA_ROOT}/ckpts/CLIP/ViT-B-32.pt
  scheduler: DPMSolver++
  num_inference_steps: 25
  augment_ratio: 5
  constraint_value: 0.8
  strength: 0.1
  root_dir: ${DIFFDA_ROOT}/DiffDA-Eval/generated_images
