exp_name: GEN_gif_skin_shot50
task: generation
seed: 0

data:
  dataset: Skin-50
  root: ${DIFFDA_ROOT}/datasets
  resolution: 512
  num_classes: 7
  examples_per_class: -1

generation:
  method: GIF
  sd_model: ${DIFFDA_ROOT}/ckpts/stable-diffusion-v1-5
  clip_model: ${DIFFDA_ROOT}/ckpts/CLIP/ViT-B-32.pt
  scheduler: DPMSolver++
  num_inference_steps: 25
  augment_ratio: 5
  strength: 0.3
  constraint_value: 0.1
  root_dir: ${DIFFDA_ROOT}/DiffDA-Eval/generated_images
  ti_embeds: ${DIFFDA_ROOT}/DiffDA-Eval/finetuned_generators/text_inversion/Skin-50_shot-1_seed0
  db_lora_weights: ${DIFFDA_ROOT}/DiffDA-Eval/finetuned_generators/dreambooth/TEmb_Skin-50_shot-1_seed0
